// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5191),
                            Details = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa.jpg",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5200)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5202),
                            Details = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa.jpg",
                            ImageUrl = "",
                            Name = "Royal Villa2",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5202)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5203),
                            Details = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa.jpg",
                            ImageUrl = "",
                            Name = "Royal Villa3",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5204)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5205),
                            Details = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa.jpg",
                            ImageUrl = "",
                            Name = "Royal Villa4",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5205)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5206),
                            Details = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa.jpg",
                            ImageUrl = "",
                            Name = "Royal Villa5",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2023, 2, 19, 1, 13, 1, 705, DateTimeKind.Local).AddTicks(5207)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
